### ISSUE TITLE
Few questions about fault localization

### ISSUE THREAD

**Issue by Iroski** [mxx1219/TRANSFER#2]
Hi I just finished reading your article and browsed the code in the fault localization section, I found something I don't quite understand and wanted to ask you. I'm just getting started in this field, so please bear with me if I'm asking some stupid questions. :)

1. I found that the data in spectrum.pkl seems to be less than the number of lines running in gzoltar. For example, the Lang_1 bug has 88 tests covering 1731 lines of code. But in spectrum.pkl, the data of Lang_1 is only an array with shape [3,38]. Among them, 3 represents the suspicious score given by the ochiai, dstar, and tarantula algorithms. I don't understand what 38 stands for, I guess it as the number of lines of code, but why is there only 38 instead of 1731. Is there a mistake in my interpretation somewhere?

2. If the number 38 in the first question represents a total of 38 lines of code, in the src_code.pkl file, each line in the 38 lines of Lang_1 bug represents a complete method, and I found that there are many methods that are repeated . What is the understanding of this piece? What is the meaning of 'This statement is not in a method'?

thank you very much

**Comment by mxx1219** [comment]
Hi there, thanks for your interest in our work!

1) You are right, Lang_1 does contain a total of 1731 lines of code. The file we provide only consists of the lines whose suspicious scores are larger than 0. Specifically, there are 38 lines whose suspicious scores are  larger than 0 in Lang_1, and you can see if your GZoltar results are consistent.  If a statement has a suspicious score of 0, it means that no failed test cases ever executed it, so we ignore these lines in our experiments.

2) Each element in spectrum.pkl file corresponds to the same-index element in src_code.pkl file. Each element in the latter represents a method, where the current focused line is annotated with keywords "rank2fixstart" and "rank2fixend".  Theoretically, each element has a different annotating position due to different lines focused, so even if they look similar, they are still different.

3) "This statement is not in a method" means there are some statements which do not  belong to any method declarations, such as the statements for class field declarations, etc. These statements can also appear in GZoltar results.

**Comment by Iroski** [comment]
> Hi there, thanks for your interest in our work!
> 
> 1. You are right, Lang_1 does contain a total of 1731 lines of code. The file we provide only consists of the lines whose suspicious scores are larger than 0. Specifically, there are 38 lines whose suspicious scores are  larger than 0 in Lang_1, and you can see if your GZoltar results are consistent.  If a statement has a suspicious score of 0, it means that no failed test cases ever executed it, so we ignore these lines in our experiments.
> 2. Each element in spectrum.pkl file corresponds to the same-index element in src_code.pkl file. Each element in the latter represents a method, where the current focused line is annotated with keywords "rank2fixstart" and "rank2fixend".  Theoretically, each element has a different annotating position due to different lines focused, so even if they look similar, they are still different.
> 3. "This statement is not in a method" means there are some statements which do not  belong to any method declarations, such as the statements for class field declarations, etc. These statements can also appear in GZoltar results.

Thank you very much, I understand the above. But based on your answer above, I have a new confusion: It seems that your 38-line suspicious score for Lang_1 is based on ochiai. So in the experiments of the paper, are other comparative experiments such as ochiai, dstar and even deepfl performed on the original spectrum (1700 lines) or after compression (38 lines)?

**Comment by mxx1219** [comment]
All use the after compression version.  Use Ochiai algorithm first to determine the compressed lines of each bug version, and then all other FL methods use the same suspicious line sets of each bug version as Ochiai.

**Comment by Iroski** [comment]
> All use the after compression version. Use Ochiai algorithm first to determine the compressed lines of each bug version, and then all other FL methods use the same suspicious line sets of each bug version as Ochiai.

I got it. Thank you!

**Comment by mxx1219** [comment]
You're welcome. Feel free to talk to me if you have any questions later.
