### ISSUE TITLE
Meaning of checker_info.pkl

### ISSUE THREAD

**Issue by hoshimiyaki** [mxx1219/TRANSFER#5]
Hello, I have read your code together with dataset. In the d4j data I found checker_info.pkl, I would like to know the meaning of that. My guess is that 1 represents the bug type which may exist in the method.

Thanks!

**Comment by mxx1219** [comment]
Thanks for your interest in our work!

The structure of checker_info.pkl is as follows:
--- A dictionary, the key of which is one of the 395 bug versions in defects4j dataset (e.g. Chart_1).
------ All suspisious lines of the selected bug version (e.g. Chart_1 has 629 suspicious lines).
--------- A list of boolean values (0 or 1) to represent whether the current suspicious line contains the necessary syntax ingredients specified in Table-1 in the paper.

For example, `checker_info["Chart_1"][0][0] = 1` indicates that the first suspicious line of Chart_1 contains the necessary syntax ingredients required by the first fix template `InsertMissedStmt`. We mentioned in the paper that before putting the test sample into the model for prediction, we filter whether the current sample contains the necessary syntax ingredients specified by each fix template. If the ingredients do not exist, we directly set the selection probability of the corresponding template to zero, because they are syntactically mismatched and impossible to generate correct patches.
